version: '3.3'

services:

  tg_bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
    depends_on:
      - postgresql

  postgresql:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DATABASE=${DB_DATABASE}
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}

    volumes:
      - ./postgres_data/:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432